### ISSUE TITLE
Mac 64-bit systems

### ISSUE THREAD

**Issue by pawh** [quandl/excel#1]
installing the plug in on a 64-bit mac os x system fails. 

<img width="432" alt="screen shot 2016-09-13 at 13 16 19" src="https://cloud.githubusercontent.com/assets/22170850/18471975/bcf195a0-79b4-11e6-8fe8-c654b632d570.png">

**Comment by lynnyen88** [comment]
Hello,

Thanks for the message. Please note that our Excel add-in is not supported on the Mac. Here's the reference to that information: http://help.quandl.com/article/245-what-versions-of-excel-does-the-quandl-excel-add-in-support

Thanks,
Lynn
